/* ===== Agents — review-first: "Needs your review" up top, then Running, Queue, FAQ ===== */
/* person → handover initials: RD = RC (Roman), FF = FC (Flo) */
var HANDOVER_INITIALS = { RD: "RC", FF: "FC" };

/* Safe minimal markdown renderer — escapes HTML first, then applies inline formatting.
   Supports: ## headings, **bold**, `code`, [label](url) / bare https:// links, - bullets.
   Returns an array of React elements. No XSS: raw text is always escaped before any
   HTML injection, and only fixed structural tags are injected. */
function renderMarkdown(text) {
  if (!text || !text.trim()) return null;

  /* 1. Escape HTML entities in a plain string */
  function esc(s) {
    return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;");
  }

  /* 2. Apply inline formatting to an already-escaped string → inner HTML string.
        Links are converted BEFORE bold/code so [] and () are still unescaped. */
  function inlineHtml(s) {
    /* [label](url) → <a> */
    s = s.replace(
      /\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g,
      function(_, label, href) {
        return '<a href="' + esc(href) + '" target="_blank" rel="noreferrer">' + label + '</a>';
      }
    );
    /* bare https?:// URLs — only outside anchors generated by the markdown-link pass above.
       Split on any <a ...>...</a> already present, autolink only the non-anchor segments. */
    s = s
      .split(/(<a\b[^>]*>.*?<\/a>)/g)
      .map(function(part, i) {
        if (i % 2 === 1) return part; /* odd indices = the <a> tags — leave untouched */
        return part.replace(
          /(^|[\s(])(https?:\/\/[^\s<)"]+)/g,
          function(_, pre, url) {
            return pre + '<a href="' + esc(url) + '" target="_blank" rel="noreferrer">' + url + '</a>';
          }
        );
      })
      .join("");
    s = s.replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>");
    s = s.replace(/`([^`]+)`/g, '<code class="ag-md-code">$1</code>');
    return s;
  }

  var lines = text.split(/\r?\n/);
  var out = [];
  var listItems = [];
  var key = 0;

  function flushList() {
    if (!listItems.length) return;
    out.push(
      React.createElement("ul", { key: key++, className: "ag-md-list" },
        listItems.map(function(li, i) {
          return React.createElement("li", { key: i,
            dangerouslySetInnerHTML: { __html: inlineHtml(esc(li)) } });
        })
      )
    );
    listItems = [];
  }

  for (var i = 0; i < lines.length; i++) {
    var line = lines[i];

    /* heading: #, ## or ### */
    var hm = line.match(/^(#{1,3})\s+(.+)/);
    if (hm) {
      flushList();
      var lvl = hm[1].length === 1 ? "h3" : hm[1].length === 2 ? "h4" : "h5";
      out.push(React.createElement(lvl, { key: key++, className: "ag-md-h",
        dangerouslySetInnerHTML: { __html: inlineHtml(esc(hm[2])) } }));
      continue;
    }

    /* bullet: - or * */
    var lm = line.match(/^[-*]\s+(.*)/);
    if (lm) { listItems.push(lm[1]); continue; }

    /* blank line: flush list */
    if (!line.trim()) { flushList(); continue; }

    /* normal paragraph */
    flushList();
    out.push(React.createElement("p", { key: key++, className: "ag-md-p",
      dangerouslySetInnerHTML: { __html: inlineHtml(esc(line)) } }));
  }
  flushList();
  return out;
}

/* ReviewCard — hoisted to module scope so React never remounts it on AgentsView
   rerenders (nested var definitions recreate component identity every render,
   wiping in-flight send-back textarea state). Receives deps as explicit props. */
function AgentReviewCard(props) {
  var t = props.t, ws = props.ws, openTask = props.openTask, person = props.person;
  var sbState = React.useState(false);
  var sbOpen = sbState[0], setSbOpen = sbState[1];
  var sbTextState = React.useState("");
  var sbVal = sbTextState[0], setSbVal = sbTextState[1];

  var evidence = t.evidence && t.evidence.trim() ? t.evidence : null;

  return (
    <div className="ag-rev-card">
      <div className="ag-rev-head">
        {t.lane && <span className={"ag-lane-chip ag-lane-" + t.lane}>{t.lane}</span>}
        {t.dealCode && <span className="ag-rev-deal">{t.dealCode}</span>}
        {ws && <span className="ag-rev-ws">{ws.name}</span>}
        <span className="ag-rev-id">{t.id}</span>
      </div>
      <div className="ag-rev-title" onClick={function() { openTask(t.id); }}>{t.text}</div>
      {t.ac && <div className="ag-rev-ac"><b>Done when:</b> {t.ac}</div>}
      <div className="ag-rev-evlabel">Result / evidence</div>
      {evidence
        ? <div className="ag-rev-ev">{renderMarkdown(evidence)}</div>
        : <div className="ag-rev-noev">No evidence posted yet.</div>}

      {/* Inline send-back panel — stays mounted, no modal, real textarea */}
      {sbOpen && (
        <div className="ag-sb-panel">
          <label className="ag-sb-label">What should the agent do differently?</label>
          <textarea
            className="ag-sb-textarea"
            rows={9}
            placeholder="Describe the issue and what to change…"
            value={sbVal}
            onChange={function(e) { setSbVal(e.target.value); }}
            autoFocus
          />
          <div className="ag-sb-actions">
            <button className="btn" onClick={function() { setSbOpen(false); setSbVal(""); }}>Cancel</button>
            <button className="btn reject" onClick={function() {
              api.verdict(t, "reject", sbVal.trim());
              setSbOpen(false); setSbVal("");
            }}>Send back</button>
          </div>
        </div>
      )}

      <div className="ag-rev-actions">
        <button className="btn approve" onClick={function() {
          var initials = HANDOVER_INITIALS[person] || person;
          api.save(t, { owners: [initials] }).then(function(ok) {
            if (ok !== false) api.verdict(t, "approve");
          });
        }}><Icon name="check" size={14} /> Approve</button>
        {!sbOpen && (
          <button className="btn reject" onClick={function() { setSbOpen(true); }}>Send back</button>
        )}
      </div>
    </div>
  );
}

/* AgentCard — hoisted for the same reason as AgentReviewCard */
function AgentQueueCard(props) {
  var t = props.t, ws = props.ws, queuePosition = props.queuePosition, openTask = props.openTask;
  var r = readiness(t);
  var qpos = (t.status === "open") ? queuePosition[t.id] : null;
  var st = (t.status === "in_progress")
    ? { label: "Running", cls: "ag-running", icon: "bolt" }
    : { label: "Queued", cls: "ag-queued", icon: "table" };
  return (
    <div className={"ag-card " + st.cls}>
      <div className="ag-card-top">
        <span className={"ag-state-badge " + st.cls}><Icon name={st.icon} size={11} /> {st.label}</span>
        {qpos && <span className="ag-queue-pos">#{qpos}</span>}
        {t.lane && <span className={"ag-lane-chip ag-lane-" + t.lane}>{t.lane}</span>}
        {ws && <span className="ag-card-ws">{ws.name}</span>}
      </div>
      <div className="ag-card-title tc-click" onClick={function() { openTask(t.id); }}>{t.text}</div>
      {t.ac && <div className="ag-card-ac"><b>Done when:</b> {t.ac}</div>}
      {t.status === "in_progress" && t.claimed_by && <div className="ag-card-meta">Claimed by {t.claimed_by}</div>}
      {t.status === "open" && r === "red" && t.need && <div className="ag-card-blocked">Blocked: {t.need}</div>}
      {t.status === "open" && r === "green" && <div className="ag-card-ready">Ready to pick up</div>}
    </div>
  );
}

function AgentsView({ openTask, person }) {
  var allAgents = TASKS.filter(function(t) { return t.execution === "agent"; });
  /* prefilter the lane to the logged-in person: Roman (RD) → RC, Flo (FF) → FC */
  var laneState = React.useState(HANDOVER_INITIALS[person] || "all");
  var laneVal = laneState[0], setLane = laneState[1];
  /* re-prefilter if the active person changes mid-session (person-switch toggle) */
  React.useEffect(function() { setLane(HANDOVER_INITIALS[person] || "all"); }, [person]);
  var agents = laneVal === "all" ? allAgents : allAgents.filter(function(t) { return t.lane === laneVal; });
  var recent = agents.filter(function(t) { return t.status === "done"; }).slice(-5).reverse();
  var showRecentState = React.useState(false);
  var showRecentVal = showRecentState[0], setShowRecent = showRecentState[1];
  var showFaqState = React.useState(false);
  var showFaqVal = showFaqState[0], setShowFaq = showFaqState[1];

  /* lane filter counts — active tasks only, ignore current filter */
  var laneN = function(l) {
    return allAgents.filter(function(t) {
      return t.status !== "done" && (l === "all" || t.lane === l);
    }).length;
  };
  var LANES = [["all", "All"], ["RC", "RC"], ["FC", "FC"]];

  var review = agents.filter(function(t) { return t.status === "in_review"; });
  var running = agents.filter(function(t) { return t.status === "in_progress" && t.claimed_by; });
  var queued = agents.filter(function(t) { return t.status === "open"; });

  var parseId = function(id) { return parseInt((id || "").replace("t-", ""), 10) || 0; };
  var queuedSorted = queued.slice().sort(function(a, b) {
    if (a.sortOrder !== b.sortOrder) return a.sortOrder - b.sortOrder;
    return parseId(a.id) - parseId(b.id);
  });
  var queuePosition = {};
  queuedSorted.forEach(function(t, i) { queuePosition[t.id] = i + 1; });

  var wsFor = function(t) {
    var d = DELIVERABLES.find(function(d) { return d.id === t.d; });
    if (!d) return null;
    return WORKSTREAMS.find(function(w) { return w.id === d.ws; });
  };

  return (
    <div className="agq">
      {/* ---- Lane filter (RC / FC) ---- */}
      <div className="ag-lanebar">
        <span className="ag-lanebar-label">Lane</span>
        <div className="ag-seg">
          {LANES.map(function(l) {
            return (
              <button key={l[0]} className={"ag-seg-btn" + (laneVal === l[0] ? " on" : "")}
                onClick={function() { setLane(l[0]); }}>
                {l[1]} <span className="ag-seg-n">{laneN(l[0])}</span>
              </button>
            );
          })}
        </div>
      </div>

      {/* ---- Needs your review ---- */}
      <section className="ag-sec">
        <h2 className="ag-sec-h">
          Needs your review
          {review.length > 0 && <span className="ag-sec-count ag-count-attn">{review.length}</span>}
        </h2>
        {review.length > 0
          ? review.map(function(t) {
              return <AgentReviewCard key={t.id} t={t} ws={wsFor(t)} openTask={openTask} person={person} />;
            })
          : <div className="ag-sec-empty">Nothing waiting on you. Finished agent tasks land here for approval.</div>}
      </section>

      {/* ---- Running ---- */}
      {running.length > 0 && (
        <section className="ag-sec">
          <h2 className="ag-sec-h">Running <span className="ag-sec-count">{running.length}</span></h2>
          <div className="ag-cards">
            {running.map(function(t) {
              return <AgentQueueCard key={t.id} t={t} ws={wsFor(t)} queuePosition={queuePosition} openTask={openTask} />;
            })}
          </div>
        </section>
      )}

      {/* ---- Queue ---- */}
      <section className="ag-sec">
        <h2 className="ag-sec-h">Queue <span className="ag-sec-count">{queued.length}</span></h2>
        {queuedSorted.length > 0
          ? <div className="ag-cards">
              {queuedSorted.map(function(t) {
                return <AgentQueueCard key={t.id} t={t} ws={wsFor(t)} queuePosition={queuePosition} openTask={openTask} />;
              })}
            </div>
          : <div className="ag-sec-empty">Queue empty. Add a task with execution <b>Claude (agent)</b>, or run <code>/repuro:queue</code>.</div>}
      </section>

      {/* ---- Recently completed — collapsible, same .ag-sec pattern ---- */}
      {recent.length > 0 && (
        <section className="ag-sec">
          <h2 className="ag-sec-h ag-sec-h--toggle" onClick={function() { setShowRecent(!showRecentVal); }}>
            <span className={"caret" + (showRecentVal ? " open" : "")}><Icon name="chevron" size={13} /></span>
            Recently completed
            <span className="ag-sec-count">{recent.length}</span>
          </h2>
          {showRecentVal && (
            <div className="ag-cards">
              {recent.map(function(t) {
                return (
                  <div key={t.id} className="ag-card ag-done tc-click" onClick={function() { openTask(t.id); }}>
                    <div className="ag-card-top">
                      <span className="ag-state-badge ag-done-badge"><Icon name="check" size={11} /> Done</span>
                    </div>
                    <div className="ag-card-title">{t.text}</div>
                  </div>
                );
              })}
            </div>
          )}
        </section>
      )}

      {/* ---- How to set up & run /repuro — collapsible, same .ag-sec pattern ---- */}
      <section className="ag-sec">
        <h2 className="ag-sec-h ag-sec-h--toggle" onClick={function() { setShowFaq(!showFaqVal); }}>
          <span className={"caret" + (showFaqVal ? " open" : "")}><Icon name="chevron" size={13} /></span>
          How to set up &amp; run <code className="ag-sec-code">/repuro</code>
        </h2>
        {showFaqVal && (
          <ol className="ag-faq-body">
            <li><b>What it is.</b> Agent tasks are run by Claude via the <code>/repuro</code> plugin — it executes the task and posts the result above for your verdict. Nothing auto-closes.</li>
            <li><b>Set up once</b> (in Claude Code): <code>/plugin marketplace add pavlovs/repuro-cockpit-skills</code> → <code>/plugin install repuro</code> → <code>/repuro:setup &lt;your-token&gt;</code>. No clone, no scripts — ask Roman for your token; it sets your lane (RC / FC) automatically.</li>
            <li><b>Run it.</b> <code>/repuro:queue</code> lists your lane; <code>/repuro:run &lt;id | #position | words&gt;</code> claims and runs one task. Add <code>--all</code> to work across both lanes.</li>
            <li><b>Review.</b> Results appear under <b>Needs your review</b> above — <b>Approve</b> to close, or <b>Send back</b> with feedback to re-queue.</li>
            <li><b>Repo</b> (auto-updates): <a href="https://github.com/pavlovs/repuro-cockpit-skills" target="_blank" rel="noreferrer">github.com/pavlovs/repuro-cockpit-skills</a></li>
          </ol>
        )}
      </section>
    </div>
  );
}
window.AgentsView = AgentsView;
