/* ===== Agents — review-first: "Needs your review" up top, then Running, Queue, FAQ ===== */
/* person (initials) → their agent-lane label, from the server's users.represents
   mapping (window.LANES: user id -> lane label, e.g. rd -> RC). Data-driven —
   onboarding a new person + runner never touches this file. */
function laneOfPerson(p) {
  var person = PEOPLE[p];
  return (person && LANES[person.userId]) || null;
}

/* Safe minimal markdown renderer — escapes HTML first, then applies inline formatting.
   Supports: ## headings, **bold**, `code`, [label](url) / bare https:// links, - bullets.
   Returns an array of React elements. No XSS: raw text is always escaped before any
   HTML injection, and only fixed structural tags are injected. */
function renderMarkdown(text) {
  if (!text || !text.trim()) return null;

  /* 1. Escape HTML entities in a plain string — quotes INCLUDED, because
     escaped text is also interpolated into href="" attribute context; an
     unescaped quote there breaks out of the attribute (stored XSS via
     uploaded .md previews — codex 2026-07-05 #3). */
  function esc(s) {
    return s.replace(/&/g, "&amp;").replace(/</g, "&lt;").replace(/>/g, "&gt;")
      .replace(/"/g, "&quot;").replace(/'/g, "&#39;");
  }

  /* 2. Apply inline formatting to an already-escaped string → inner HTML string.
        Links are converted BEFORE bold/code so [] and () are still unescaped. */
  function inlineHtml(s) {
    /* [label](url) → <a> */
    s = s.replace(
      /\[([^\]]+)\]\((https?:\/\/[^\s)]+)\)/g,
      function(_, label, href) {
        return '<a href="' + esc(href) + '" target="_blank" rel="noreferrer">' + label + '</a>';
      }
    );
    /* bare https?:// URLs — only outside anchors generated by the markdown-link pass above.
       Split on any <a ...>...</a> already present, autolink only the non-anchor segments. */
    s = s
      .split(/(<a\b[^>]*>.*?<\/a>)/g)
      .map(function(part, i) {
        if (i % 2 === 1) return part; /* odd indices = the <a> tags — leave untouched */
        return part.replace(
          /(^|[\s(])(https?:\/\/[^\s<)"]+)/g,
          function(_, pre, url) {
            return pre + '<a href="' + esc(url) + '" target="_blank" rel="noreferrer">' + url + '</a>';
          }
        );
      })
      .join("");
    s = s.replace(/\*\*(.+?)\*\*/g, "<strong>$1</strong>");
    s = s.replace(/`([^`]+)`/g, '<code class="ag-md-code">$1</code>');
    return s;
  }

  var lines = text.split(/\r?\n/);
  var out = [];
  var listItems = [];
  var key = 0;

  function flushList() {
    if (!listItems.length) return;
    out.push(
      React.createElement("ul", { key: key++, className: "ag-md-list" },
        listItems.map(function(li, i) {
          return React.createElement("li", { key: i,
            dangerouslySetInnerHTML: { __html: inlineHtml(esc(li)) } });
        })
      )
    );
    listItems = [];
  }

  for (var i = 0; i < lines.length; i++) {
    var line = lines[i];

    /* heading: #, ## or ### */
    var hm = line.match(/^(#{1,3})\s+(.+)/);
    if (hm) {
      flushList();
      var lvl = hm[1].length === 1 ? "h3" : hm[1].length === 2 ? "h4" : "h5";
      out.push(React.createElement(lvl, { key: key++, className: "ag-md-h",
        dangerouslySetInnerHTML: { __html: inlineHtml(esc(hm[2])) } }));
      continue;
    }

    /* bullet: - or * */
    var lm = line.match(/^[-*]\s+(.*)/);
    if (lm) { listItems.push(lm[1]); continue; }

    /* blank line: flush list */
    if (!line.trim()) { flushList(); continue; }

    /* normal paragraph */
    flushList();
    out.push(React.createElement("p", { key: key++, className: "ag-md-p",
      dangerouslySetInnerHTML: { __html: inlineHtml(esc(line)) } }));
  }
  flushList();
  return out;
}

/* ArtifactPreview — renders the uploaded artifact preview inline by type:
   .pdf → embedded viewer, .md → fetched + rendered with renderMarkdown,
   .html → sandboxed iframe, images → <img>. The reviewer reads the actual
   output in the card, not a file path. */
function ArtifactPreview(props) {
  var url = props.url;
  var mdState = React.useState(null);
  var mdText = mdState[0], setMdText = mdState[1];
  var isMd = /\.md$/i.test(url);

  React.useEffect(function() {
    if (!isMd) return;
    var alive = true;
    setMdText(null);
    fetch(url)
      .then(function(r) { return r.ok ? r.text() : "Preview could not be loaded (" + r.status + ")"; })
      .then(function(txt) { if (alive) setMdText(txt); })
      .catch(function() { if (alive) setMdText("Preview could not be loaded."); });
    return function() { alive = false; };
  }, [url]);

  if (/\.pdf$/i.test(url)) {
    return (
      <object data={url} type="application/pdf" className="ag-rev-pdf">
        <a href={url} target="_blank" rel="noreferrer">Open PDF</a>
      </object>
    );
  }
  if (isMd) {
    return (
      <div className="ag-rev-mdprev">
        {mdText === null ? <span className="ag-card-no-ev">Loading preview…</span> : renderMarkdown(mdText)}
      </div>
    );
  }
  /* .html previews are no longer uploadable (stored-XSS vector) — the server
     force-downloads any legacy ones; everything else renders as an image */
  return <img src={url} className="ag-rev-img" alt="Preview" />;
}

/* ReviewCard — hoisted to module scope so React never remounts it on AgentsView
   rerenders (nested var definitions recreate component identity every render,
   wiping in-flight send-back textarea state). Receives deps as explicit props. */
function AgentReviewCard(props) {
  var t = props.t, ws = props.ws, openTask = props.openTask, person = props.person;
  var fbState = React.useState("");
  var fbVal = fbState[0], setFbVal = fbState[1];

  var canWriteAgents = !!(window.COCKPIT && (window.COCKPIT.isAdmin || (window.COCKPIT.perms && window.COCKPIT.perms.agents === "rw")));
  var evidence = t.evidence && t.evidence.trim() ? t.evidence : null;
  var hasPreview = !!t.previewUrl;
  var roundLabel = t.reviewRound > 0 ? "Round " + (t.reviewRound + 1) : null;

  /* Parse AC into checklist items if present */
  var acItems = null;
  if (t.ac) {
    acItems = t.ac.split(/[;\n]/).map(function(s) { return s.trim(); }).filter(Boolean);
  }

  return (
    <div className="ag-rev-card ag-rev-card--v2">
      {/* ---- Verdict bar (full width, top) ---- */}
      <div className="ag-rev-verdict">
        <div className="ag-rev-verdict-left">
          <span className="ag-rev-badge ag-rev-badge--review">
            <Icon name="bolt" size={12} /> In Review
          </span>
          {roundLabel && <span className="ag-rev-round">{roundLabel}</span>}
          {t.lane && <span className={"ag-lane-chip ag-lane-" + t.lane}>{t.lane}</span>}
          {t.dealCode && <span className="ag-rev-deal">{t.dealCode}</span>}
          {ws && <span className="ag-rev-ws">{ws.name}</span>}
        </div>
        <span className="ag-rev-id">{t.id}</span>
      </div>

      <div className="ag-rev-title" onClick={function() { openTask(t.id); }}>{t.text}</div>

      {/* AC checklist */}
      {acItems && (
        <div className="ag-rev-ac-list">
          <span className="ag-rev-ac-label">Acceptance criteria</span>
          {acItems.map(function(item, i) {
            return <div key={i} className="ag-rev-ac-item"><Icon name="check" size={11} /> {item}</div>;
          })}
        </div>
      )}

      {/* on a redo: the instruction the agent was sent back with (verifier AC9) */}
      {t.reviewRound > 0 && t.reviewFeedback && (
        <div className="ag-card-feedback"><b>Your feedback (R{t.reviewRound}):</b> {t.reviewFeedback}</div>
      )}

      {/* ---- Split: left (summary) + right (preview) ---- */}
      <div className={hasPreview ? "ag-rev-split" : "ag-rev-split ag-rev-split--full"}>
        <div className="ag-rev-left">
          <div className="ag-rev-evlabel">Summary &amp; evidence</div>
          {evidence
            ? <div className="ag-rev-ev">{renderMarkdown(evidence)}</div>
            : <div className="ag-rev-noev">No evidence posted yet.</div>}
        </div>

        {hasPreview && (
          <div className="ag-rev-right">
            <div className="ag-rev-evlabel">Artifact preview</div>
            <div className="ag-rev-preview-wrap">
              <ArtifactPreview url={t.previewUrl} />
            </div>
            <a href={t.previewUrl} target="_blank" rel="noreferrer" className="ag-rev-open-link">
              <Icon name="arrow" size={12} /> Open in browser
            </a>
          </div>
        )}
      </div>

      {/* ---- Feedback bar (full width, bottom) ---- */}
      <div className="ag-rev-feedback">
        <textarea
          className="ag-rev-fb-text"
          rows={3}
          placeholder="Commentary / feedback for the agent…"
          value={fbVal}
          onChange={function(e) { setFbVal(e.target.value); }}
        />
        {canWriteAgents && (
        <div className="ag-rev-fb-actions">
          <button className="btn approve" onClick={function() {
            var initials = laneOfPerson(person) || person;
            api.save(t, { owners: [initials] }).then(function(ok) {
              if (ok !== false) api.verdict(t, "approve", fbVal.trim() || undefined);
            });
            setFbVal("");
          }}><Icon name="check" size={14} /> Approve</button>
          <button className="btn ag-btn-changes" onClick={function() {
            if (!fbVal.trim()) { showToast("Add feedback before requesting changes", "err"); return; }
            api.requestChanges(t, fbVal.trim());
            setFbVal("");
          }}><Icon name="bolt" size={14} /> Request Changes</button>
          <button className="btn reject" onClick={function() {
            api.verdict(t, "reject", fbVal.trim() || undefined);
            setFbVal("");
          }}>Reject</button>
          <button className="btn ag-btn-escalate" onClick={function() {
            api.save(t, { execution: "together" }).then(function(ok) {
              if (ok !== false) {
                api.verdict(t, "reject", "[ESCALATED] " + (fbVal.trim() || "Needs human pair-work"));
              }
            });
            setFbVal("");
          }}>Escalate</button>
        </div>
        )}
      </div>
    </div>
  );
}

/* Lease freshness for a running task — amber once under 60 min so a stalled
   agent is visible from the Queue tab (SPEC v2 §7, Opus MUST). */
function leaseInfo(t) {
  if (!t.claim_expires_at) return null;
  var mins = Math.round((new Date(t.claim_expires_at) - Date.now()) / 60000);
  if (mins <= 0) return { label: "lease expired", stale: true };
  return { label: "lease " + (mins >= 90 ? Math.round(mins / 60) + "h" : mins + "m"), stale: mins < 60 };
}

/* RunningCard — pinned on top of the Queue view: who runs what, is it alive */
function AgentRunningCard(props) {
  var t = props.t, ws = props.ws, openTask = props.openTask;
  var lease = leaseInfo(t);
  return (
    <div className="ag-card ag-running">
      <div className="ag-card-top">
        <span className="ag-state-badge ag-running"><Icon name="bolt" size={11} /> Running</span>
        {t.reviewRound > 0 && <span className="ag-round-chip">Round {t.reviewRound + 1}</span>}
        {t.lane && <span className={"ag-lane-chip ag-lane-" + t.lane}>{t.lane}</span>}
        {ws && <span className="ag-card-ws">{ws.name}</span>}
        {lease && <span className={"ag-lease-chip" + (lease.stale ? " stale" : "")}>{lease.label}</span>}
      </div>
      <div className="ag-card-title tc-click" onClick={function() { openTask(t.id); }}>{t.text}</div>
      {t.claimed_by && <div className="ag-card-meta">Claimed by {t.claimed_by}</div>}
    </div>
  );
}

/* AgentQueueRow — compact single-line queue entry (Opus MUST: density, not
   location, is the "long queue" fix). No AC text — the drawer has it. */
function AgentQueueRow(props) {
  var t = props.t, pos = props.pos, openTask = props.openTask;
  var r = readiness(t);
  return (
    <div className="ag-qrow tc-click" onClick={function() { openTask(t.id); }}>
      <span className="ag-qrow-pos">#{pos}</span>
      <span className="ag-qrow-title">{t.text}</span>
      {t.reviewRound > 0 && <span className="ag-round-chip">R{t.reviewRound + 1}</span>}
      {t.lane && <span className={"ag-lane-chip ag-lane-" + t.lane}>{t.lane}</span>}
      {t.dealCode && <span className="ag-qrow-deal">{t.dealCode}</span>}
      {r === "red"
        ? <span className="ag-qrow-state ag-qrow-blocked">blocked</span>
        : <span className="ag-qrow-state ag-qrow-ready">ready</span>}
    </div>
  );
}

/* HelpPanel — the setup guide, reachable ONLY via the "?" header affordance
   (Opus MUST: docs get a labeled home, not a burial under another tab). */
function AgentsHelpPanel(props) {
  return (
    <div className="ag-help-scrim" onClick={props.onClose}>
      <div className="ag-help-panel" onClick={function(e) { e.stopPropagation(); }}>
        <div className="ag-help-head">
          <h3>How to set up &amp; run <code className="ag-sec-code">/repuro</code></h3>
          <button className="btn" onClick={props.onClose}>Close</button>
        </div>
        <ol className="ag-faq-body">
          <li><b>What it is.</b> Agent tasks are run by Claude via the <code>/repuro</code> plugin — it executes the task and posts the result to <b>Inbox</b> for your verdict. Nothing auto-closes.</li>
          <li><b>Set up once</b> (in Claude Code): <code>/plugin marketplace add pavlovs/repuro-cockpit-skills</code> → <code>/plugin install repuro</code> → <code>/repuro:setup &lt;your-token&gt;</code>. Ask Roman for your token; it sets your lane (RC / FC) automatically. Update later with <code>/plugin update repuro@repuro</code>.</li>
          <li><b>Run it.</b> <code>/repuro:loop</code> drains your whole queue (also runs on a schedule); <code>/repuro:run &lt;id | #position | words&gt;</code> runs one task; <code>/repuro:add</code> queues a new task from any session. Add <code>--all</code> to work across both lanes.</li>
          <li><b>Review — everything happens in the Inbox, not in the terminal.</b> <b>Approve</b> closes a task, <b>Request changes</b> sends it back with your feedback (the next loop pass redoes it), <b>Reject</b> takes it off the agent lane. Agent questions appear as <b>Waiting on you</b> — answer inline and the task re-queues itself.</li>
          <li><b>Playbook.</b> Runners propose one-line lessons; adopt or dismiss them in the Inbox. Adopted rules ride with every future run (hard = binding, soft = default).</li>
          <li><b>Repo:</b> <a href="https://github.com/pavlovs/repuro-cockpit-skills" target="_blank" rel="noreferrer">github.com/pavlovs/repuro-cockpit-skills</a></li>
        </ol>
      </div>
    </div>
  );
}

/* AgentBlockedCard — "Waiting on you": the agent parked this task on a question.
   Inline answer -> task re-opens -> next runner pass picks it up (SPEC §7c). */
function AgentBlockedCard(props) {
  var t = props.t, ws = props.ws, openTask = props.openTask;
  var ansState = React.useState("");
  var ansVal = ansState[0], setAns = ansState[1];
  var busyState = React.useState(false);
  var busyVal = busyState[0], setBusy = busyState[1];
  var canWriteAgents = !!(window.COCKPIT && (window.COCKPIT.isAdmin || (window.COCKPIT.perms && window.COCKPIT.perms.agents === "rw")));

  var submit = function() {
    if (!ansVal.trim()) { showToast("Type an answer first", "err"); return; }
    if (busyVal) return;
    setBusy(true);
    api.answerBlocker(t, ansVal.trim()).then(function(ok) {
      setBusy(false);
      if (ok) { setAns(""); showToast("Answered — back in the queue for the next run", "info"); }
    });
  };

  return (
    <div className="ag-card ag-waiting-card">
      <div className="ag-card-top">
        <span className="ag-state-badge ag-waiting-badge"><Icon name="bolt" size={11} /> Waiting on you</span>
        {t.reviewRound > 0 && <span className="ag-round-chip">Round {t.reviewRound + 1}</span>}
        {t.lane && <span className={"ag-lane-chip ag-lane-" + t.lane}>{t.lane}</span>}
        {ws && <span className="ag-card-ws">{ws.name}</span>}
      </div>
      <div className="ag-card-title tc-click" onClick={function() { openTask(t.id); }}>{t.text}</div>
      {t.inputQuestion
        ? (
          <React.Fragment>
            <div className="ag-waiting-q">{t.inputQuestion}</div>
            <div className="ag-waiting-answer">
              <input
                className="ag-waiting-input"
                placeholder="Your answer — the agent continues with this…"
                value={ansVal}
                onChange={function(e) { setAns(e.target.value); }}
                onKeyDown={function(e) { if (e.key === "Enter") submit(); }}
              />
              {canWriteAgents && (
              <button className="btn approve" disabled={busyVal} onClick={submit}>
                <Icon name="check" size={13} /> {busyVal ? "Sending…" : "Answer & requeue"}
              </button>
              )}
            </div>
          </React.Fragment>
        )
        : <div className="ag-card-blocked">Blocked without a question — open the task to resolve.</div>}
    </div>
  );
}

/* LessonRow — one proposed lesson: promote (optionally after inline edit) or
   dismiss. Candidates come from runners; NOTHING enters the playbook without a
   human click, and the playbook is hard-capped server-side (40). */
function LessonRow(props) {
  var l = props.l;
  var editState = React.useState(l.text);
  var editVal = editState[0], setEdit = editState[1];
  var canWriteAgents = !!(window.COCKPIT && (window.COCKPIT.isAdmin || (window.COCKPIT.perms && window.COCKPIT.perms.agents === "rw")));
  /* resync the draft when the server text changes (SSE refresh mutates the
     lesson object in place) — otherwise a stale draft can be adopted */
  React.useEffect(function() { setEdit(l.text); }, [l.id, l.text]);
  return (
    <div className="ag-lesson-row">
      <span className={"ag-lesson-kind ag-lesson-" + l.kind}>{l.kind === "constraint" ? "hard" : "soft"}</span>
      <input className="ag-lesson-text" value={editVal}
        onChange={function(e) { setEdit(e.target.value); }} />
      {l.source_task && <span className="ag-lesson-src">{l.source_task}</span>}
      {canWriteAgents && (
      <button className="btn approve" onClick={function() {
        api.decideLearning(l, "promote", editVal.trim() || l.text);
      }}><Icon name="check" size={12} /> Adopt</button>
      )}
      {canWriteAgents && (
      <button className="btn" onClick={function() { api.decideLearning(l, "dismiss"); }}>Dismiss</button>
      )}
    </div>
  );
}

function AgentsView({ openTask, person }) {
  var allAgents = TASKS.filter(function(t) { return t.execution === "agent"; });
  /* Admins see every lane (prefiltered to their own); non-admins only ever
     receive their OWN agent workflows from the server — no lane bar for them. */
  var isAdmin = !!(window.COCKPIT && window.COCKPIT.isAdmin);
  var laneState = React.useState(isAdmin ? (laneOfPerson(person) || "all") : "all");
  var laneVal = laneState[0], setLane = laneState[1];
  /* re-prefilter if the active person changes mid-session (person-switch toggle) */
  React.useEffect(function() { if (isAdmin) setLane(laneOfPerson(person) || "all"); }, [person]);
  var agents = laneVal === "all" ? allAgents : allAgents.filter(function(t) { return t.lane === laneVal; });

  /* learnings are lane-scoped like tasks (lane = user id, null = every lane) —
     the lane filter applies to their counts and lists too (verifier AC7) */
  var LANE_KEY = {}; // lane label -> user id, e.g. RC -> rd
  Object.keys(LANES).forEach(function(uid) { LANE_KEY[LANES[uid]] = uid; });
  var laneMatch = function(l) {
    return laneVal === "all" || !l.lane || l.lane === LANE_KEY[laneVal];
  };
  var learnings = (window.LEARNINGS || []).filter(laneMatch);
  var lessonCandidates = learnings.filter(function(l) { return l.status === "candidate"; });
  var playbook = learnings.filter(function(l) { return l.status === "active"; });

  var review = agents.filter(function(t) { return t.status === "in_review"; });
  var running = agents.filter(function(t) { return t.status === "in_progress" && t.claimed_by; });
  /* statusRaw: boot.js maps blocked->open for the general views; here blocked
     tasks are "Waiting on you" items, never queue rows */
  var waiting = agents.filter(function(t) { return t.statusRaw === "blocked"; });
  var queued = agents.filter(function(t) { return t.status === "open" && t.statusRaw !== "blocked"; });
  var recent = agents.filter(function(t) { return t.status === "done"; }).slice(-8).reverse();

  /* blocking = items an agent is parked on (reviews + questions). Lessons are
     curation, not blockers — they never share the amber badge (Opus MUST). */
  var blocking = review.length + waiting.length;
  var canWriteWorkstreams = !!(window.COCKPIT && (window.COCKPIT.isAdmin || (window.COCKPIT.perms && window.COCKPIT.perms.workstreams === "rw")));

  /* sticky tabs: land on Inbox only if something blocks, else Queue; after
     that the user navigates — an action emptying the Inbox NEVER yanks the
     tab away (zero states instead). useState initializer = initial land only. */
  var tabState = React.useState(blocking > 0 ? "inbox" : "queue");
  var tabVal = tabState[0], setTab = tabState[1];
  var showRecentState = React.useState(false);
  var showRecentVal = showRecentState[0], setShowRecent = showRecentState[1];
  var helpState = React.useState(false);
  var helpVal = helpState[0], setHelp = helpState[1];

  /* lane filter counts — active tasks only, ignore current filter */
  var laneN = function(l) {
    return allAgents.filter(function(t) {
      return t.status !== "done" && (l === "all" || t.lane === l);
    }).length;
  };
  var LANE_OPTS = [["all", "All"]].concat(
    Object.keys(LANES).map(function(uid) { return [LANES[uid], LANES[uid]]; })
  );

  var parseId = function(id) { return parseInt((id || "").replace("t-", ""), 10) || 0; };
  var queuedSorted = queued.slice().sort(function(a, b) {
    if (a.sortOrder !== b.sortOrder) return a.sortOrder - b.sortOrder;
    return parseId(a.id) - parseId(b.id);
  });

  var wsFor = function(t) {
    var d = DELIVERABLES.find(function(d) { return d.id === t.d; });
    if (!d) return null;
    return WORKSTREAMS.find(function(w) { return w.id === d.ws; });
  };

  var newAgentTask = function() {
    window.dispatchEvent(new CustomEvent("cockpit:quickadd", { detail: { type: "task", execution: "agent" } }));
  };

  /* all tab badges follow the active lane filter (Opus SHOULD 6) */
  var TABS = [
    { key: "inbox", label: "Inbox", n: blocking, attn: blocking > 0, sub: lessonCandidates.length },
    { key: "queue", label: "Queue", n: queued.length, extra: running.length > 0 ? running.length + " running" : null },
    { key: "playbook", label: "Playbook", n: playbook.length },
  ];

  return (
    <div className="agq">
      {/* ---- header row: view tabs + help + lane filter ---- */}
      <div className="ag-topbar">
        <div className="ag-tabs">
          {TABS.map(function(tb) {
            return (
              <button key={tb.key} className={"ag-tab" + (tabVal === tb.key ? " on" : "")}
                onClick={function() { setTab(tb.key); }}>
                {tb.label}
                <span className={"ag-tab-n" + (tb.attn ? " attn" : "")}>{tb.n}</span>
                {tb.sub > 0 && <span className="ag-tab-sub" title="proposed lessons">·{tb.sub}</span>}
                {tb.extra && <span className="ag-tab-extra">{tb.extra}</span>}
              </button>
            );
          })}
          <button className="ag-help-btn" title="How to set up & run /repuro" onClick={function() { setHelp(true); }}>?</button>
        </div>
        {isAdmin && (
        <div className="ag-lanebar">
          <span className="ag-lanebar-label">Lane</span>
          <div className="ag-seg">
            {LANE_OPTS.map(function(l) {
              return (
                <button key={l[0]} className={"ag-seg-btn" + (laneVal === l[0] ? " on" : "")}
                  onClick={function() { setLane(l[0]); }}>
                  {l[1]} <span className="ag-seg-n">{laneN(l[0])}</span>
                </button>
              );
            })}
          </div>
        </div>
        )}
      </div>

      {/* ================= INBOX — everything that waits on a human ================= */}
      {tabVal === "inbox" && (
        <React.Fragment>
          {blocking === 0 && lessonCandidates.length === 0 && (
            <div className="ag-zero">Nothing needs you — {queued.length} queued, {running.length} running.</div>
          )}
          {review.length > 0 && (
            <section className="ag-sec">
              <h2 className="ag-sec-h">Needs your review <span className="ag-sec-count ag-count-attn">{review.length}</span></h2>
              {review.map(function(t) {
                return <AgentReviewCard key={t.id} t={t} ws={wsFor(t)} openTask={openTask} person={person} />;
              })}
            </section>
          )}
          {waiting.length > 0 && (
            <section className="ag-sec">
              <h2 className="ag-sec-h">Waiting on you <span className="ag-sec-count ag-count-attn">{waiting.length}</span></h2>
              <div className="ag-cards">
                {waiting.map(function(t) {
                  return <AgentBlockedCard key={t.id} t={t} ws={wsFor(t)} openTask={openTask} />;
                })}
              </div>
            </section>
          )}
          {lessonCandidates.length > 0 && (
            <section className="ag-sec ag-sec--subordinate">
              <h2 className="ag-sec-h ag-sec-h--sub">Proposed lessons <span className="ag-sec-count">{lessonCandidates.length}</span></h2>
              <div className="ag-lessons">
                {lessonCandidates.map(function(l) { return <LessonRow key={l.id} l={l} />; })}
              </div>
            </section>
          )}
        </React.Fragment>
      )}

      {/* ================= QUEUE — the machine's side ================= */}
      {tabVal === "queue" && (
        <React.Fragment>
          {running.length > 0 && (
            <section className="ag-sec">
              <h2 className="ag-sec-h">Running <span className="ag-sec-count">{running.length}</span></h2>
              <div className="ag-cards">
                {running.map(function(t) {
                  return <AgentRunningCard key={t.id} t={t} ws={wsFor(t)} openTask={openTask} />;
                })}
              </div>
            </section>
          )}
          <section className="ag-sec">
            <h2 className="ag-sec-h">
              Queue <span className="ag-sec-count">{queued.length}</span>
              {canWriteWorkstreams && <button className="btn ag-qadd" onClick={newAgentTask}><Icon name="plus" size={13} /> New agent task</button>}
            </h2>
            {queuedSorted.length > 0
              ? <div className="ag-qrows">
                  {queuedSorted.map(function(t, i) {
                    return <AgentQueueRow key={t.id} t={t} pos={i + 1} openTask={openTask} />;
                  })}
                </div>
              : <div className="ag-zero">Queue empty. Add a task here or <code>/repuro:add</code> from any Claude session.</div>}
          </section>
          {recent.length > 0 && (
            <section className="ag-sec">
              <h2 className="ag-sec-h ag-sec-h--toggle" onClick={function() { setShowRecent(!showRecentVal); }}>
                <span className={"caret" + (showRecentVal ? " open" : "")}><Icon name="chevron" size={13} /></span>
                Recently completed
                <span className="ag-sec-count">{recent.length}</span>
              </h2>
              {showRecentVal && (
                <div className="ag-qrows">
                  {recent.map(function(t) {
                    return (
                      <div key={t.id} className="ag-qrow ag-qrow--done tc-click" onClick={function() { openTask(t.id); }}>
                        <span className="ag-qrow-pos"><Icon name="check" size={11} /></span>
                        <span className="ag-qrow-title">{t.text}</span>
                        {t.lane && <span className={"ag-lane-chip ag-lane-" + t.lane}>{t.lane}</span>}
                      </div>
                    );
                  })}
                </div>
              )}
            </section>
          )}
        </React.Fragment>
      )}

      {/* ================= PLAYBOOK — the curated rules, nothing else ================= */}
      {tabVal === "playbook" && (
        <section className="ag-sec">
          <h2 className="ag-sec-h">Playbook <span className="ag-sec-count" title="hard cap — a full playbook forces pruning">{playbook.length} of max 40</span></h2>
          {playbook.length > 0
            ? <div className="ag-lessons">
                {playbook.map(function(l) {
                  return (
                    <div key={l.id} className="ag-lesson-row ag-lesson-row--active">
                      <span className={"ag-lesson-kind ag-lesson-" + l.kind}>{l.kind === "constraint" ? "hard" : "soft"}</span>
                      <span className="ag-lesson-static">{l.text}</span>
                      {l.source_task && <span className="ag-lesson-src">{l.source_task}</span>}
                      <button className="btn" title="Retire from playbook"
                        onClick={function() { api.decideLearning(l, "dismiss"); }}>Retire</button>
                    </div>
                  );
                })}
              </div>
            : <div className="ag-zero">No adopted rules yet. Runners propose lessons after redo rounds — adopt them in the Inbox and they ride with every future run.</div>}
        </section>
      )}

      {helpVal && <AgentsHelpPanel onClose={function() { setHelp(false); }} />}
    </div>
  );
}
window.AgentsView = AgentsView;
