"""Regenerate the cockpit-generated block in deals.md (DESIGN-SPEC §4.4).
Replaces ONLY the content between the marker comments; everything else in
deals.md stays hand-edited. Write path: temp -> verify -> os.replace (house rule).

Block content: stage snapshot of all mirrored deals (master = dealroom.db) +
open next steps for cockpit-owned deals (master = cockpit). Deals in owner_mode
'legacy' keep their execution state hand-written elsewhere in deals.md.
"""

import os
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))

from src import db  # noqa: E402

BEGIN = "<!-- cockpit:begin generated — do not hand-edit inside this block -->"
END = "<!-- cockpit:end -->"
DEALS_MD = Path(__file__).resolve().parent.parent.parent / "deals.md"


def build_block(conn):
    rows = conn.execute(
        "SELECT codename, stage, note, owner_mode, synced_at FROM deal_mirror "
        "ORDER BY codename"
    ).fetchall()
    if not rows:
        return f"{BEGIN}\n*(no deals mirrored yet — run `cockpit.py sync`)*\n{END}"
    synced = max((r["synced_at"] or "") for r in rows)
    lines = [
        BEGIN,
        f"## Pipeline status (generated by cockpit — stage master: dealroom.db, synced {synced})",
        "",
        "| Deal | Stage | Owner | Note |",
        "|---|---|---|---|",
    ]
    for r in rows:
        note = (r["note"] or "").splitlines()[0][:80] if r["note"] else ""
        note = note.replace("|", "\\|")  # raw pipe would break the table (PM M2-M4 R5)
        lines.append(
            f"| {r['codename']} | {r['stage'] or '—'} | {r['owner_mode']} | {note} |"
        )
    owned = [r["codename"] for r in rows if r["owner_mode"] == "cockpit-owned"]
    lines.append("")
    if owned:
        lines.append("### Open next steps (cockpit-owned deals)")
        for codename in owned:
            tasks = conn.execute(
                "SELECT text, deadline, status FROM tasks WHERE deal=? AND staging=0 "
                "AND status NOT IN ('done') ORDER BY deadline",
                (codename,),
            ).fetchall()
            lines.append(f"**{codename}**")
            lines += [
                f"- {t['text']} ({t['deadline'] or 'no date'}, {t['status']})"
                for t in tasks
            ] or ["- (no open tasks)"]
    else:
        lines.append(
            "*(no deals cockpit-owned yet — execution state still lives in the "
            "hand-written sections above; deals flip at curation)*"
        )
    lines.append(END)
    return "\n".join(lines)


def main():
    deals_path = Path(os.environ.get("COCKPIT_DEALS_MD", DEALS_MD))
    init = "--init" in sys.argv
    text = deals_path.read_text(encoding="utf-8")
    block = build_block(db.get_conn())
    n_begin, n_end = text.count(BEGIN), text.count(END)
    # fail-closed on marker drift (PM M2-M4 R4): silently appending a second block
    # would recreate the two-truths problem this script exists to kill
    if n_begin == 1 and n_end == 1 and text.index(BEGIN) < text.index(END):
        pre, rest = text.split(BEGIN, 1)
        _, post = rest.split(END, 1)
        new_text = pre + block + post
    elif n_begin == 0 and n_end == 0 and init:
        new_text = text.rstrip() + "\n\n---\n\n" + block + "\n"
    elif n_begin == 0 and n_end == 0:
        raise SystemExit(
            "no cockpit markers in deals.md — run with --init for first insertion"
        )
    else:
        raise SystemExit(
            f"marker drift in deals.md (begin={n_begin}, end={n_end}) — fix by hand, not writing"
        )
    if BEGIN not in new_text or len(new_text) < len(block):
        raise SystemExit("sanity check failed — not writing")
    tmp = deals_path.with_suffix(".md.cockpit-tmp")
    tmp.write_text(new_text, encoding="utf-8")
    if tmp.stat().st_size == 0:
        raise SystemExit("temp file empty — not replacing")
    os.replace(tmp, deals_path)
    print(f"deals.md generated block updated ({len(block.splitlines())} lines)")


if __name__ == "__main__":
    main()
